services:
  patients-service:
    build: 
      context: .
      dockerfile: Dockerfile.app.template
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle_db:1521/XE
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: oracle_password
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ~/.m2:/root/.m2  # Maven cache
      - ./target:/app/target
    depends_on:
      oracle_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  oracle_db:
    image: gvenzl/oracle-xe:18.4.0-slim
    environment:
      ORACLE_PASSWORD: oracle_password # Sets the password for SYSTEM, SYS, PDBADMIN
      # ORACLE_DATABASE: APP # Optionally, create a database (not typical for XE which has a fixed one)
      # APP_USER: medical_user # This image can create a user with this name
      # APP_USER_PASSWORD: medical_password # Password for APP_USER
    ports:
      - "1521:1521"
      - "5500:5500" # For EM Express if available
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1521"] # Basic TCP port check
      interval: 30s # Increased interval for Oracle
      timeout: 10s
      retries: 5
    restart: unless-stopped

  pipeline-watcher:
    image: eclipse-temurin:17-jdk-jammy
    volumes:
      - .:/workspace
      - ~/.m2:/root/.m2  # Shared Maven cache
    working_dir: /workspace
    command: >
      bash -c "apt-get update && apt-get install -y inotify-tools curl &&
      while true; do
        inotifywait -r -e modify,create,delete \
          --exclude='.*(/target|\.git|\.mvn/wrapper).*' \
          ./src ./pom.xml &&
        echo 'Changes detected. Running checks...' &&
        ./mvnw verify;
      done"
    # Removed direct dependency on 'db' for pipeline-watcher, 
    # as 'mvnw verify' might not always need a live DB.
    # If tests run by 'verify' require DB, this might need to be reinstated for 'oracle_db'.

volumes:
  oracle_data: {}