name: Java 24 CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: medical_db
          POSTGRES_USER: sandoval
          POSTGRES_PASSWORD: salessa
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set executable permissions
      run: chmod +x ./mvnw  # Adicione esta linha
      
    - name: Setup Java 24 (Early Access)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '24-ea'
        check-latest: true
        
    - name: Validate Java version
      run: java -version
      
    - name: Build with Maven
      run: |
        ./mvnw -B package \
          -Dmaven.compiler.release=24 \
          -Dmaven.compiler.parameters=true \
          -Dmaven.compiler.showWarnings=true
      env:
        MAVEN_OPTS: "--add-opens jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED --enable-preview"
          
    - name: Build with Maven
      run: ./mvnw -B package --file pom.xml -DskipTests
      env:
        MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
      
    - name: Run Tests
      run: ./mvnw test
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/medical_db
        SPRING_DATASOURCE_USERNAME: sandoval
        SPRING_DATASOURCE_PASSWORD: salessa
